name: App Android Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'XX.XX.XX | XX.XX.XX+XX'
        type: string
        required: true

jobs:
  build:
    name: Build APK and Create release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Update version in YAML
        run: perl -i -pe 's/((version:\s)+\d+\.\d+\.\d+)(\+\d+)?/$2 ${{  github.event.inputs.version }}/g' pubspec.yaml
      - name: Commiting changes
        uses: mikeal/publish-to-github-action@1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Create a Release in GitHub
        uses: ncipollo/release-action@v1.10.0
        with:
          token: ${{ secrets.GH_TOKEN }}
          tag: ${{ github.event.inputs.version }}
          commit: ${{ github.sha }}
          prerelease: true
