name: App Android Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'XX.XX.XX | XX.XX.XX+XX'
        type: string
        required: true

jobs:
  build:
    name: Build APK and Create release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.17.0'
      - name: Update version in YAML
        run: sed -i 's/^((version:\s)+\d+\.\d+\.\d+)(\+\d+)?$/version:\ ${{ github.event.inputs.version }}/e' pubspec.yaml
      - name: Commit changes
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Create a Release in GitHub
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GH_TOKEN }}
          tag: ${{ github.event.inputs.version }}
          commit: ${{ github.sha }}
          prerelease: true
